#!/bin/R

## r.upset-from-orthofinder.R
## Draw upset plot from Orthofinder outputs
## Amit Sinha, New England Biolabs, Ipswich (MA) 01938 USA
## 2018-02-25
## https://github.com/aWormGuy/aWormGuy

library("UpSetR")

filename <- "my_orthofider_results/Orthogroups/Orthogroups.GeneCount.tsv"; # Output generated by Orthofinder

orthofinder_df <- read.table(filename, sep="\t", header = T, stringsAsFactors = F)
colnames(orthofinder_df) 

##  [1] "Orthogroup"  "wAlbB"   "wBm"  "wBpa"   "wCfeJ"  
##  [6] "wCfeT"   "wCle"    "wCtub"   "wDcau"   "wDcitri"
## [11] "wDimm"   "wFol"    "wLsig"   "wMel"    "wMhie"  
## [16] "wMoviF"  "wMoz"    "wMpe"    "wOcae"   "wOo"    
## [21] "wOvol"   "wPpe"    "wWb"     "Total"   
     

selected_species <- colnames(orthofinder_df)[2:(ncol(orthofinder_df) -1)] # Default value  = All species

## Subset columns if not plotting all species
selected_species <- c("wCle", "wMhie", "wMoviF", "wOcae", "wMoz", "wMpe")

## Get the presence/absence matrix
orthofinder_matrix <- (orthofinder_df[,selected_species] >= 1) + 0

## convert back to df
orthofinder_mx2df <- as.data.frame(orthofinder_matrix)

## Add back the Orthogroup column
orthofinder_mx2df <- cbind(orthofinder_df$Orthogroup, orthofinder_mx2df)

## Add back the proper name for the first column
colnames(orthofinder_mx2df)[1] <- "Orthogroup"

## Various upset plots

# (1) 
upset(orthofinder_mx2df, nsets = ncol(orthofinder_mx2df), sets = selected_species, keep.order = T)

# (2) 
upset(orthofinder_mx2df, nsets = ncol(orthofinder_mx2df), sets = rev(selected_species), keep.order = T)

# (3)
upset(orthofinder_mx2df, nsets = ncol(orthofinder_mx2df), order.by="freq")

# (4) Save the plot in an object
( final_upset <- upset(orthofinder_mx2df, nsets = ncol(orthofinder_mx2df), 
	order.by="degree", 
	nintersects= NA,
	sets = selected_species, 
	keep.order = T, 
	sets.x.label = "Number of orthogroups"
	) 
)
# Print the plot object to pdf/tiff etc
pdf("my_upset_plot.pdf")
print(final_upset)
dev.off()

# Further polishing can be done by editing the pdf in Adobe Illustrator
## e.g. : Change axes titles, Colring a subset of bars, etc
# *-*-*

